### ISSUE TITLE
Move away from using the Kubelet/Wrapper to a unit flie

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cross-cloud#12]
Currently our deployments are using the kubelet/wrapper for starting the kubelet component of hyperkube https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html which relies on using rkt to start kubelet. Kubelet will then start the remaining k8s components using the Docker container engine. We should look at switching this wrapper out and using a unit file so we are only using a single container engine.

**Comment by lixuna** [comment]
ready to close, @dlx
