### ISSUE TITLE
Create Relese Repo for Prometheus/CoreDNS/Kuberenetes and Fetch/Deploy CI Created Artifacts

### ISSUE THREAD

**Issue by dlx** [cncf/cross-cloud#17]
Create Release Repo https://gitlab.cncf.ci/cncf/releases so that when a CI Build Job for Prometheus/CoreDNS/Kuberenetes is run, the artifacts and it's build version will be stored so it can be used for deploying/testing on a k8s cluster with Helm.

**Comment by lixuna** [comment]
ready to close, @dlx
