### ISSUE TITLE
Build Prometheus Binaries needed for chart stable/prometheus

### ISSUE THREAD

**Issue by hh** [cncf/cross-cloud#20]
```
repository: prom/alertmanager
repository: prom/node-exporter
repository: prom/prometheus
```

**Comment by hh** [comment]
Create ci-vX.Y.Z branches that include your .gitlab-ci.yml for:

https://github.com/prometheus/prometheus/releases/tag/v1.6.3
https://github.com/prometheus/node_exporter/releases/tag/v0.14.0
https://github.com/prometheus/alertmanager/releases/tag/v0.6.2

https://gitlab.cncf.ci/prometheus/prometheus/blob/ci-v1.6.3/.gitlab-ci.yml
https://gitlab.cncf.ci/prometheus/alertmanager/blob/ci-v0.6.2/.gitlab-ci.yml
https://gitlab.cncf.ci/prometheus/node_exporter/blob/ci-v0.14.0/.gitlab-ci.yml

**Comment by zilman** [comment]
Done
