### ISSUE TITLE
Design Doc?

### ISSUE THREAD

**Issue by jbeda** [cncf/cross-cloud#23]
Is there any documentation on what this is or how it works?

**Comment by dankohn** [comment]
Jo, we haven't forgotten you. The team is trying to get an initial version up in the next several days and then will write up a Readme explaining what they've done and their plans ahead.

**Comment by jbeda** [comment]
Very cool!  Just trying to figure out what's up.  Thanks!

**Comment by hh** [comment]
Creating a PR to start on this now.

**Comment by hh** [comment]
WIP #30 Opened

**Comment by hh** [comment]
This is a public draft, though I went ahead and pulled in an early draft to master:

https://docs.google.com/document/d/1swK7-QJmyHzfUATsNp6zhcrtOqifPXDgpYDuemfsr0k/
which is being collected into:
https://github.com/cncf/cross-cloud/pull/31

**Comment by taylor** [comment]
Thank you for your feedback @jbeda which we are incorporating within the project documentation.

We are closing this ticket as we will be addressing the questions in several areas of the documentation, including:
- Getting started (new section in README)
  - TL;DR for how to use cross-cloud  => https://github.com/cncf/cross-cloud/issues/53
  - How to use cross-cloud? => https://github.com/cncf/cross-cloud/issues/54
  - How to add your project to cross-cloud? => https://github.com/cncf/cross-cloud/issues/55
- FAQ => https://github.com/cncf/cross-cloud/issues/51
- Roadmap => https://github.com/cncf/cross-cloud/issues/56
- Technical Architecture Design => https://github.com/cncf/cross-cloud/issues/57
