### ISSUE TITLE
Kubernetes is not Resolving External Domain Names

### ISSUE THREAD

**Issue by dlx** [cncf/cross-cloud#28]
Kubernetes should be able to resolve External Domain Names our k8s e2e test also show that this is failing.

**Comment by zilman** [comment]
On this issue specify which cloud, even if it's all.

**Comment by dlx** [comment]
Unsure what clouds are effected at the moment we will need to investigate further but this isn't causing any troubles yet so adding to the Backlog.

**Comment by dlx** [comment]
Switched out Kube-DNS with CoreDNS and External names are now resolving on aws/packet.
