### ISSUE TITLE
Kudernetes v1.6.3 apiserver By Default uses etcd3 and will fail to fall back to use etcd2

### ISSUE THREAD

**Issue by dlx** [cncf/cross-cloud#4]
Open Issue Here https://github.com/streamplace/kube-for-mac/pull/2

Fix is to start the api Server with the flag
--storage-backend=etcd2

**Comment by hh** [comment]
Thanks for fixing this @dlx 

https://github.com/cncf/cross-cloud/commit/a9db0851b4d20aeaf26dcc5a15f5646a20c67016
